### PR TITLE
Feature newsweek

### PR DESCRIPTION
**Pull request by tnyandoro**
Please review our project
This project is a replica of the news site Newsweek.com using the Bootstrap framework.
We have developed this project using HTML 5, CSS 3, and bootstrap for responsiveness

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet.😟 You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [ ]  Fix Linter issues

- [ ] Fix HTML validation  You can check HTML validations in validator.w3.org

- [ ] Your clone have side margin  
please work on it so it looks like the original one 
chrome-capture (33)

- [ ] Your navbar has a lot of widths. please work on it so it looks like the original one 
chrome-capture (34)

- [ ] Remove extra space from here. please work on it so it looks like the original one 
chrome-capture (35)

- [ ] you have more than 1 US & World sections. please remove extra ones and create those which are present on the original page.

- [ ] your clone is the missing footer. please have a look below
chrome-capture (36)

**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi 
Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
### Navbar
- [ ] Make navbar responsive and disply issue at 340px 

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://inspiring-mestorf-3a414e.netlify.app/)|
|:---:|:---:|
|source-page|clone|

- [ ] Make navbar responsive and disply issue at 5700px 

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://inspiring-mestorf-3a414e.netlify.app/)|
|:---:|:---:|
|source-page|clone|
- [ ] Make navbar responsive and disply issue at 340px 
- [ ] Remove User Icon
- [ ] Add `SIGN IN` button

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://inspiring-mestorf-3a414e.netlify.app/)|
|:---:|:---:|
|source-page|clone|


### Magzine
- [ ] Magzine section is not responsive to small screens

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://inspiring-mestorf-3a414e.netlify.app/)|
|:---:|:---:|
|source-page|clone|

### Subscription
- [ ] Text should be overflow on images in small screens

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://inspiring-mestorf-3a414e.netlify.app/)|
|:---:|:---:|
|source-page|clone|

### Newsletter
- [ ] Please try to proper design according to original

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://inspiring-mestorf-3a414e.netlify.app/)|
|:---:|:---:|
|source-page|clone|

### Footer
- [ ] Fix the footer issues on all screens

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://inspiring-mestorf-3a414e.netlify.app/)|
|:---:|:---:|
|source-page|clone|


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet.😟 You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [ ] Your clone have side margin
please work on it so it looks like the original one 
chrome-capture (33)

- [ ] Your navbar has a lot of widths. please work on it so it looks like the original one 
chrome-capture (34)

- [ ] Remove extra space from here. please work on it so it looks like the original one 
chrome-capture (35)

- [ ] footer content is not align correctly. please have a look on the original page. 

**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by arslanbisharat — APPROVED** [review]
### Congratulations APPROVED :clap:
Hello I can see you worked really hard on this project. and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
_The clone shows a good understanding and usage of HTML CSS💯_

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

- [ ] **Optional**  Your footer is not align correctly. Please make it as present on the original page. 
chrome-capture (20)

chrome-capture (21)


[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

**Pull request merged**
